package GreedIsland.Animations;

// Lista de animatii disponibile (practic asignam un nume fiecarui ID de animatie pe care il vom folosi
public enum AnimationList
{
    heroWalkUp,
    heroWalkDown,
    heroWalkRight,
    heroWalkLeft,
    heroIdleUp,
    heroIdleDown,
    heroIdleRight,
    heroIdleLeft,
    heroAttackLeft,
    heroAttackRight,
    heroAttackUp,
    heroAttackDown,
    wolfWalkUp,
    wolfWalkDown,
    wolfWalkRight,
    wolfWalkLeft,
    wolfIdleUp,
    wolfIdleDown,
    wolfIdleRight,
    wolfIdleLeft,
    orcWalkUp,
    orcWalkDown,
    orcWalkRight,
    orcWalkLeft,
    orcIdleUp,
    orcIdleDown,
    orcIdleRight,
    orcIdleLeft,
    skeletonWalkUp,
    skeletonWalkDown,
    skeletonWalkRight,
    skeletonWalkLeft,
    skeletonIdleUp,
    skeletonIdleDown,
    skeletonIdleRight,
    skeletonIdleLeft
}
